name: "Tests"

on:
  pull_request: # Workflow only runs for PR against main anyway
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: 'QHUB_GH_BRANCH set to PR'
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "QHUB_GH_BRANCH=1${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_REF: ${GITHUB_REF}"

      - name: 'QHUB_GH_BRANCH set to branch (not a tag)'
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
        run: |
          echo "QHUB_GH_BRANCH=2${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: 'print QHUB_GH_BRANCH'
        run: |
          echo "BRANCH ${QHUB_GH_BRANCH}"

